// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_M_wMmH8nYj4OOvs46-_f6Xb0jk_g4vA',
    appId: '1:525008174022:web:23c8bc7e10dcc8258810c7',
    messagingSenderId: '525008174022',
    projectId: 'allcare-55fc4',
    authDomain: 'allcare-55fc4.firebaseapp.com',
    storageBucket: 'allcare-55fc4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtaGvkiXxZu4QjSLVMFiSLD0x2_XJuP84',
    appId: '1:525008174022:android:4321847ab482982d8810c7',
    messagingSenderId: '525008174022',
    projectId: 'allcare-55fc4',
    storageBucket: 'allcare-55fc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIjxjtlsmUcqc20hYLDuVA2vS9dFiDNRI',
    appId: '1:525008174022:ios:ff62a01470b197228810c7',
    messagingSenderId: '525008174022',
    projectId: 'allcare-55fc4',
    storageBucket: 'allcare-55fc4.appspot.com',
    iosClientId: '525008174022-bsr5i13eimh793qf0a4a730bjd9fkrcn.apps.googleusercontent.com',
    iosBundleId: 'com.allcare.allcareapp',
  );
}
